openapi: 3.0.0
info:
  title: swagger
  version: 1.0.0
paths:
  '{{base_url}}/api/users/login':
    post:
      summary: Login Users
      operationId: >-
        home_aditya-bachawad_documents_bruno_sdcms_-_server_sdcms_-_server_collections_authentication_login_users_yml
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      requestBody:
        $ref: '#/components/requestBodies/login_users'
  '{{base_url}}/api/users/register':
    post:
      summary: Register New User
      operationId: >-
        home_aditya-bachawad_documents_bruno_sdcms_-_server_sdcms_-_server_collections_authentication_register_new_user_yml
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      requestBody:
        $ref: '#/components/requestBodies/register_new_user'
  '{{base_url}}/api/users/profile':
    get:
      summary: USER Profile @private
      operationId: >-
        home_aditya-bachawad_documents_bruno_sdcms_-_server_sdcms_-_server_collections_authentication_user_profile_private_yml
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      security:
        - user_profile_private: []
servers: []
components:
  schemas:
    login_users:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: operator@example.com
        password: '123456'
    register_new_user:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: Aditya
        email: aditya@example.com
        password: '123456'
  requestBodies:
    login_users:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/login_users'
      description: ''
      required: true
    register_new_user:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/register_new_user'
      description: ''
      required: true
  securitySchemes:
    user_profile_private:
      type: http
      scheme: bearer
