name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      backend_branch:
        description: 'Backend branch to deploy (SDCMS-Server)'
        required: true
        default: 'staging'
      frontend_branch:
        description: 'Frontend branch to deploy (SDCMS-Web-App)'
        required: true
        default: 'staging'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy branches
        run: /var/www/deploy.sh ${{ github.event.inputs.backend_branch }} ${{ github.event.inputs.frontend_branch }}
